AllCops:
  TargetRubyVersion: 2.4

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
    Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/NumericPredicate:
  Enabled: false
